CREATE USER EMPLOYEE_SERVICE
IDENTIFIED BY employee_password;

GRANT CONNECT, RESOURCE TO EMPLOYEE_SERVICE;

ALTER USER EMPLOYEE_SERVICE
QUOTA UNLIMITED ON USERS;


CREATE USER PAYROLL_SERVICE
IDENTIFIED BY payroll_password;

GRANT CONNECT, RESOURCE TO PAYROLL_SERVICE;

ALTER USER PAYROLL_SERVICE
QUOTA UNLIMITED ON USERS;